# constants/constants.py

from configparser import ConfigParser

config = ConfigParser()
config.read('config/config.ini')

class LoginPageLocators:
    LOGIN_BTN = config['LOCATORS']['LOGIN_BTN_XPATH']
    EMAIL_INPUT = config['LOCATORS']['EMAIL_INPUT_XPATH']
    PASSWORD_INPUT = config['LOCATORS']['PASSWORD_INPUT_XPATH']
    FORGOT_PASSWORD = config['LOCATORS']['FORGOT_PASSWORD_XPATH']
    GOOGLE_LOGIN_BTN = config['LOCATORS']['GOOGLE_LOGIN_BTN_XPATH']
    FACEBOOK_LOGIN_BTN = config['LOCATORS']['FACEBOOK_LOGIN_BTN_XPATH']
    LINKEDIN_LOGIN_BTN = config['LOCATORS']['LINKEDIN_LOGIN_BTN_XPATH']
    TWITTER_LOGIN = config['LOCATORS']['TWITTER_LOGIN_XPATH']
    INSTAGRAM_LOGIN = config['LOCATORS']['INSTAGRAM_LOGIN_XPATH']
    NEW_VOLUNTEER_REGISTRATION = config['LOCATORS']['NEW_VOLUNTEER_REGISTRATION_XPATH']
    DATE_FIELD_LOGIN_PAGE = config['LOCATORS']['DATE_FIELD_LOGIN_PAGE_XPATH']
    LOCATION_FIELD = config['LOCATORS']['LOCATION_FIELD_XPATH']
    LOGIN_ERROR = config['LOCATORS']['LOGIN_ERROR_XPATH']
    INVALID_PASS_ERR = config['LOCATORS']['INVALID_PASS_ERR_XPATH']
    EYE_BTN_PASS_FIELD = config['LOCATORS']['EYE_BTN_PASS_FIELD_CSS']


class URLs:
    BASE_URL = config['URLS']['BASE_URL']
    FORGOT_PASSWORD_URL = config['URLS']['FORGOT_PASSWORD_URL']
    EXPECTED_URL_AFTER_LOGIN = config['URLS']['EXPECTED_URL_AFTER_LOGIN']

class Messages:
    REQ_FIELD = config['MESSAGES']['REQ_FIELD']
    WELCOME_TEXT1 = config['MESSAGES']['WELCOME_TEXT1']
    WELCOME_TEXT2 = config['MESSAGES']['WELCOME_TEXT2']
    HINDI_TEXT = config['MESSAGES']['HINDI_TEXT']
