import time

from ddt import ddt
import pytest
from cchc_automation.pythonProject2.pageObject.userr.Register_page.reegis import Register
from selenium.webdriver.common.alert import Alert
import configparser
from cchc_automation.pythonProject2.Base.email_random import Random

from selenium.webdriver.support.wait import WebDriverWait

config = configparser.ConfigParser()
config.read("C://Users//Anuj//cchc_automation//pythonProject2//Utilities//.properties")


@pytest.mark.usefixtures("setup")
@ddt
class Test_Ccc_Register_Page:
    def test_without_any_data(self):
        register = Register(self.driver)
        register.register_button()
        register.Create_button()
        time.sleep(3)
        register.validate_form()
        time.sleep(2)

    def test_input_all_data(self):
        register = Register(self.driver)
        random_email = Random().generate_random_email()
        random_mobile = Random().generate_random_mobile_number()
        register.register_button()
        time.sleep(1)
        register.name_input(config.get("Credentials", "username"))
        time.sleep(1)
        register.email_input(random_email)
        time.sleep(1)
        register.phone_input(random_mobile)
        time.sleep(1)
        register.address_input(config.get("Credentials", "address"))
        time.sleep(1)
        register.aadhar_number_input(config.get("Credentials", "aadhar_number"))
        time.sleep(1)
        register.password_input(config.get("Credentials", "password"))
        time.sleep(1)
        register.confirm_password_input(config.get("Credentials", "confirm_password"))
        time.sleep(1)
        register.choose_profile_picture(config.get("Credentials", "profile_picture"))
        time.sleep(1)
        register.select_category_checkbox()
        time.sleep(1)
        register.eye_icon1()
        time.sleep(1)
        register.eye_icon2()
        time.sleep(1)
        register.Create_button()
        print("2")
        time.sleep(1)

    def test_without_email(self):
        register = Register(self.driver)
        # random_email = Random().generate_random_email()
        register.register_button()
        time.sleep(1)
        register.name_input(config.get("Credentials", "username"))
        # time.sleep(1)
        time.sleep(1)
        register.phone_input(config.get("Credentials", "mobile_number"))
        time.sleep(1)
        register.address_input(config.get("Credentials", "address"))
        time.sleep(1)
        register.aadhar_number_input(config.get("Credentials", "aadhar_number"))
        time.sleep(1)
        register.password_input(config.get("Credentials", "password"))
        time.sleep(1)
        register.confirm_password_input(config.get("Credentials", "confirm_password"))
        time.sleep(1)
        register.choose_profile_picture(config.get("Credentials", "profile_picture"))
        time.sleep(1)
        register.select_category_checkbox()
        time.sleep(1)
        register.eye_icon1()
        time.sleep(1)
        register.eye_icon2()
        time.sleep(1)
        register.Create_button()
        time.sleep(1)
        register.validate_form()
        time.sleep(2)

    def test_without_password(self):
        register = Register(self.driver)
        random_email = Random().generate_random_email()
        random_mobile = Random().generate_random_mobile_number()

        register.register_button()
        time.sleep(1)
        register.name_input(config.get("Credentials", "username"))
        time.sleep(1)
        register.email_input(random_email)
        time.sleep(1)
        register.phone_input(random_mobile)
        time.sleep(1)
        register.address_input(config.get("Credentials", "address"))
        time.sleep(1)
        register.aadhar_number_input(config.get("Credentials", "aadhar_number"))
        time.sleep(2)
        register.choose_profile_picture(config.get("Credentials", "profile_picture"))
        time.sleep(1)
        register.select_category_checkbox()
        time.sleep(1)
        register.eye_icon1()
        time.sleep(1)
        register.eye_icon2()
        time.sleep(1)
        register.Create_button()
        time.sleep(1)
        register.password_required_field_error_message_field()
        time.sleep(2)

    def test_email_already_registered(self):
        register = Register(self.driver)
        random_mobile = Random().generate_random_mobile_number()
        register.register_button()
        time.sleep(2)
        register.name_input(config.get("Credentials", "username"))
        time.sleep(1)
        register.email_input(config.get("Credentials", "email"))
        time.sleep(1)
        register.phone_input(random_mobile)
        time.sleep(1)
        register.address_input(config.get("Credentials", "address"))
        time.sleep(1)
        register.aadhar_number_input(config.get("Credentials", "aadhar_number"))
        time.sleep(1)
        register.password_input(config.get("Credentials", "password"))
        time.sleep(1)
        register.confirm_password_input(config.get("Credentials", "confirm_password"))
        time.sleep(1)
        register.choose_profile_picture(config.get("Credentials", "profile_picture"))
        time.sleep(1)
        register.select_category_checkbox()
        time.sleep(1)
        register.eye_icon1()
        time.sleep(1)
        register.eye_icon2()
        time.sleep(1)
        register.Create_button()
        time.sleep(1)
        register.email_already_exits_error_message()
        time.sleep(1)

    def test_mobile_already_registered(self):
        register = Register(self.driver)
        random_email = Random().generate_random_email()
        register.register_button()
        time.sleep(1)
        register.name_input(config.get("Credentials", "username"))
        time.sleep(1)
        register.email_input(random_email)
        time.sleep(1)
        register.phone_input(config.get("Credentials", "mobile_number"))
        time.sleep(1)
        register.address_input(config.get("Credentials", "address"))
        time.sleep(1)
        register.aadhar_number_input(config.get("Credentials", "aadhar_number"))
        time.sleep(1)
        register.password_input(config.get("Credentials", "password"))
        time.sleep(1)
        register.confirm_password_input(config.get("Credentials", "confirm_password"))
        time.sleep(1)
        register.choose_profile_picture(config.get("Credentials", "profile_picture"))
        time.sleep(1)
        register.select_category_checkbox()
        time.sleep(1)
        register.eye_icon1()
        time.sleep(1)
        register.eye_icon2()
        time.sleep(1)
        register.Create_button()
        time.sleep(1)
        # register.invalid_mobile_number_error()
        time.sleep(20)

    def test_only_select_category(self):
        register = Register(self.driver)
        register.register_button()
        register.select_category_checkbox()
        time.sleep(2)
        register.Create_button()
        time.sleep(2)
        register.validate_form()
        time.sleep(3)

    def test_only_upload_profile_picture(self):
        register = Register(self.driver)
        register.register_button()
        time.sleep(1)
        register.choose_profile_picture(config.get("Credentials", "profile_picture"))
        register.Create_button()
        time.sleep(1)
        register.validate_form()
        time.sleep(3)


    def test_click_login_button(self):
        register = Register(self.driver)
        register.register_button()
        time.sleep(2)
        register.login_here_button()
        time.sleep(3)




    # def test_check_confirm_password_and_password(self):
    #     register = Register(self.driver)
    #     random_email = Random().generate_random_email()
    #     random_mobile = Random().generate_random_mobile_number()
    #     register.register_button()
    #     time.sleep(1)
    #     register.name_input(config.get("Credentials", "username"))
    #     time.sleep(1)
    #     register.email_input(random_email)
    #     time.sleep(1)
    #     register.phone_input(random_mobile)
    #     time.sleep(1)
    #     register.address_input(config.get("Credentials", "address"))
    #     time.sleep(1)
    #     register.aadhar_number_input(config.get("Credentials", "aadhar_number"))
    #
    #     time.sleep(5)
    #     password = config.get('Credentials', 'password')
    #     confirm_password = config.get('Credentials', 'confirm_password')
    #     register.check_confirm_password(password,confirm_password)
    #
    #     time.sleep(1)
    #     # register.password_input(config.get("Credentials", "password"))
    #     # time.sleep(1)
    #     # register.confirm_password_input(config.get("Credentials", "confirm_password"))
    #     # time.sleep(1)
    #     register.choose_profile_picture(config.get("Credentials", "profile_picture"))
    #     time.sleep(1)
    #     register.select_category_checkbox()
    #     time.sleep(1)
    #     register.eye_icon1()
    #     time.sleep(1)
    #     register.eye_icon2()
    #     time.sleep(1)
    #     register.Create_button()
